apiVersion: batch/v1
kind: Job
metadata:
  name: portfolio-migrate
  namespace: portfolio
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
        - name: migrate
          image: rizkysiregar/react-web-resume:v1.0.0
          command: ["npx", "prisma", "migrate", "deploy", "--schema=src/data/prisma/schema.prisma"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: portfolio-db-secret
                  key: DATABASE_URL
      restartPolicy: Never
