apiVersion: v1
kind: Secret
metadata:
  name: portfolio-db-secret
  namespace: portfolio
type: Opaque
stringData:
  DATABASE_URL: "postgresql://infra_dev_admin:siregar123@192.168.1.50:5433/dev_admin"
